# Generated by Django 4.2.3 on 2023-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_accessoriesrequesttowh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesrequesttowh',
            name='style_po_id',
            field=models.CharField(max_length=100),
        ),
    ]
