# Generated by Django 4.2.3 on 2023-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_accessoriesrequesttowh_style_po_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequesttowh',
            name='request_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
