# Generated by Django 4.2.3 on 2023-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_accessoriesrequesttowh_request_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseToProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_po_id', models.CharField(max_length=100)),
                ('style_po', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('handover_quantity', models.PositiveIntegerField(default=0)),
                ('request_qty', models.IntegerField(default=0)),
                ('request_by', models.CharField(max_length=100)),
                ('request_line', models.CharField(max_length=100)),
                ('handover_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
