# Generated by Django 4.2.3 on 2023-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_warehousetoproductionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetoproductionhistory',
            name='operator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
