# Generated by Django 4.2.3 on 2023-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_warehousetoproductionhistory_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetoproductionhistory',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
