# Generated by Django 4.2.3 on 2023-07-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_warehousetoproductionhistory_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricInventoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('po_style_no', models.CharField(blank=True, max_length=200, null=True)),
                ('receive_qty', models.PositiveIntegerField(default=0)),
                ('receive_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('accinv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fabricinventoy')),
            ],
        ),
        migrations.CreateModel(
            name='FabricComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_construction', models.CharField(blank=True, max_length=200, null=True)),
                ('fabric_width', models.CharField(blank=True, max_length=200, null=True)),
                ('fabric_composition', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('receive_qty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accinv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fabricinventoy')),
            ],
        ),
    ]
