# Generated by Django 4.2.3 on 2023-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fabricinventoy_fabricimage_fabriccomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricRequesttoWH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
