# Generated by Django 4.2.3 on 2023-08-03 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fabricrequesttowh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='po_style_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='request_fabric_roll',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='request_fabric_width',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='request_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='request_usr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabricrequesttowh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
